### PR TITLE
chore!: Upgrade to ocm v0.3.0

### PR DESCRIPTION
**Pull request by jakobmoellerdev**
**Description**

Changes proposed in this pull request:

- removes the legacy oci types
- upgrades to ocm v0.3.0
- introduces better context registrations for resolving types from moduleTemplate descriptor

WARNING: Introduces lots of dependencies in the graph that are probably not good, e.g. the previously removed helm is reintroduced in OCM. I believe OCM has tons of unnecessary deps for us which could be invoked as false positives in sec scannings. Still TBD how to get these down. Also had to pin docker version otherwise we would have a breaking go mod graph, still experimenting

WARNING: Should not be merged until all Module Templates are generated with OCM v3alpha1 scheme, as the v2 scheme still generates the old localOciBlob access type in the CLI. aligned with @ruanxin 

**Related issue(s)**
#841

### CODE REVIEW

**Comment by ruanxin** [comment]
This PR was blocked until we fully migrated ModuleTemplate component descriptor from v2 to v3alpha1

**Review by jeremyharisch — APPROVED** [review]

**Pull request merged**
