### PR TITLE
fix: remove virtual service

### PR DESCRIPTION
**Pull request by adityabhatia**

### CODE REVIEW

**Review by jakobmoellersap — CHANGES_REQUESTED** [review]
I think this PR needs to be rebased, could you check this?

**Comment by adityabhatia** [comment]
>

**Comment by adityabhatia** [comment]
> I think this PR needs to be rebased, could you check this?

The base branch is not `main` :)

**Comment by jakobmoellersap** [comment]
Yes I am saying you should rebase the branch `add_watcher` to main and then fork and create your pr from there

**Review by ruanxin — APPROVED** [review]

**Review by jakobmoellersap — APPROVED** [review]

**Pull request merged**
