### PR TITLE
add Provide credential for private OCI registry authentication guide

### PR DESCRIPTION
**Pull request by ruanxin**
related issue: https://github.com/kyma-project/module-manager/issues/201

### CODE REVIEW

**Review by jakobmoellersap — COMMENTED** [review]
I suggest to move the guide to the user guides, other than that will have to do a detailed review next

**Comment by ruanxin** [comment]
> I suggest to move the guide to the user guides, other than that will have to do a detailed review next

moved to `docs/user`

**Review by jakobmoellersap — COMMENTED** [review]
Nice guide :) Waiting for one more review

**Review by adityabhatia — APPROVED** [review]
Good stuff, easy to understand

**Pull request merged**
